import 'package:flutter/material.dart';
import '../../globals/colors.dart';
import '../../widgets/bottomNavigationBar.dart';
import '../../widgets/appbar.dart';
import 'package:ionicons/ionicons.dart';

class Step1 extends StatefulWidget {
  const Step1({Key? key}) : super(key: key);

  @override
  State<Step1> createState() => _Step1State();
}

class _Step1State extends State<Step1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: greyColor,
        appBar: PreferredSize(
          preferredSize: const Size.fromHeight(60),
          child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [CustomAppbar()]),
        ),
        bottomNavigationBar: bottomNavigationBar(),
        body: Column(
          children: [
            Container(
                margin: EdgeInsets.symmetric(vertical: 15),
                child: Text(
                  'Upload images',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                )),
            Container(
              alignment: Alignment.center,
              width: double.infinity,
              height: 150,
              child: AspectRatio(
                aspectRatio: 3 / 2,
                child: Container(
                  child: Icon(Ionicons.add_outline, size: 60),
                  decoration: BoxDecoration(
                      border: Border.all(color: blackColor),
                      borderRadius: BorderRadius.all(Radius.circular(25))),
                ),
              ),
            ),
            Container(
              //margin: EdgeInsets.symmetric(vertical: 10),
              margin: EdgeInsets.only(top: 15),
              height: 5 / 3,
              color: blackColor,
            ),
            Expanded(
              child: Container(
                width: double.infinity,
                child: SingleChildScrollView(
                  child: Column(children: [
                    Stack(
                      children: [
                        Container(
                          margin: EdgeInsets.only(top: 15),
                          alignment: Alignment.center,
                          width: double.infinity,
                          height: 210,
                          child: AspectRatio(
                            aspectRatio: 4 / 3,
                            child: Container(
                              child: Icon(Ionicons.add_outline, size: 60),
                              decoration: BoxDecoration(
                                  border: Border.all(color: blackColor),
                                  borderRadius:
                                      BorderRadius.all(Radius.circular(15))),
                            ),
                          ),
                        ),
                        Positioned.fill(
                            child: Container(
                          width: double.infinity,
                          height: 210,
                          child: AspectRatio(
                            aspectRatio: 4 / 3,
                          ),
                        ))
                      ],
                    ),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                    Text("sadsadasd"),
                  ]),
                ),
              ),
            )
          ],
        ));
  }
}
